### ISSUE TITLE
When will code release?

### ISSUE THREAD

**Issue by Njasa2k** [wyhsirius/LEO#1]

**Comment by Njasa2k** [comment]
Is there an expected release date?

**Comment by TruthSearcher** [comment]
+1

**Comment by wyhsirius** [comment]
@ninjasaid2k @TruthSearcher Thanks for your interest, code will be released soon.

**Comment by olliacc** [comment]
> @ninjasaid2k @TruthSearcher Thanks for your interest, code will be released soon.

any info on this?
